// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZBhcg1QnEXuBbXKjk7ZKb5qVSciVr890',
    appId: '1:409241423708:web:0690ac39ca141152577b99',
    messagingSenderId: '409241423708',
    projectId: 'garage-door-hero',
    authDomain: 'garage-door-hero.firebaseapp.com',
    storageBucket: 'garage-door-hero.firebasestorage.app',
    measurementId: 'G-V7FLVKRE6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnm8OVfRP3oSJ7vaDm29bpifVOzF8RzO4',
    appId: '1:409241423708:android:38459454e4b09414577b99',
    messagingSenderId: '409241423708',
    projectId: 'garage-door-hero',
    storageBucket: 'garage-door-hero.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLnly2uEbDbUc2dDgKfBzHzqi5uSSz4Q',
    appId: '1:409241423708:ios:d5dfca4560f9fb27577b99',
    messagingSenderId: '409241423708',
    projectId: 'garage-door-hero',
    storageBucket: 'garage-door-hero.firebasestorage.app',
    iosBundleId: 'com.example.myWebsite',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLnly2uEbDbUc2dDgKfBzHzqi5uSSz4Q',
    appId: '1:409241423708:ios:d5dfca4560f9fb27577b99',
    messagingSenderId: '409241423708',
    projectId: 'garage-door-hero',
    storageBucket: 'garage-door-hero.firebasestorage.app',
    iosBundleId: 'com.example.myWebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZBhcg1QnEXuBbXKjk7ZKb5qVSciVr890',
    appId: '1:409241423708:web:404b3be9c2c26cbd577b99',
    messagingSenderId: '409241423708',
    projectId: 'garage-door-hero',
    authDomain: 'garage-door-hero.firebaseapp.com',
    storageBucket: 'garage-door-hero.firebasestorage.app',
    measurementId: 'G-BZ39MLZT85',
  );
}
